var e = function(e, p) {
    return Object.keys(p).reduce(function(a, o) {
        var r = p[o];
        return -1 < r.indexOf("/weapp/") ? a[o] = "https://" + e["main-domain"] + r : -1 < r.indexOf("/o/wxapp/") ? a[o] = "https://" + e["market-domain"] + r : a[o] = "https://" + e["main-domain"] + r, 
        a;
    }, {});
};

module.exports = function(p) {
    return e(p, {
        login: "/weapp/v1/account/login",
        uuid: "/weapp/v1/user/uuid/register",
        poiFilter: "/weapp/v2/poi/homepage",
        homeHead: "/weapp/v1/v8/home/head",
        poiFood: "/weapp/v1/poi/food",
        poiInfo: "/weapp/v1/poi/info",
        poiFoodCollect: "/weapp/v1/food/collect",
        spuTagProducts: "/weapp/v1/poi/sputag/products",
        poiCommentInfo: "/weapp/v1/comment/poi",
        gocomment: "/weapp/v1/comment/gocomment",
        commentsubmit: "/weapp/v1/comment/submit",
        channelPage: "/weapp/v2/poi/channelpage",
        getFilterConditions: "/weapp/v1/poi/getfilterconditions",
        searchPoi: "/weapp/v2/search/v9/poi",
        searchPoiWithFilter: "/weapp/v2/search/v9/poiwithfilter",
        nonDelivery: "/weapp/v1/search/non-delivery/poi",
        searchSuggestV8: "/weapp/v1/search/v8/suggest",
        orders: "/weapp/v1/order/getuserorders",
        orderDetail: "/weapp/v1/order/detail",
        orderPindanDetail: "/weapp/v1/patchorder/detail",
        orderStatus: "/weapp/v2/order/status",
        orderPindanStatus: "/weapp/v1/patchorder/status",
        orderHistoryStatus: "/weapp/v2/order/historystatus",
        orderPreview: "/weapp/v1/order/preview",
        orderUpdate: "/weapp/v1/order/update",
        orderDeliverTime: "/weapp/v1/order/getdeliverytime",
        orderSubmit: "/weapp/v1/order/submit",
        cancelRefundComplaints: "/weapp/v1/payment/refund/cancel",
        orderConfirmReceive: "/weapp/v1/order/confirmreceive",
        orderCancel: "/weapp/v1/order/cancel",
        privacyInfo: "/weapp/v1/privacy/info",
        privacyBinding: "/weapp/v1/privacy/binding",
        previewRiskCheckResendCode: "/weapp/v1/order/preview/riskcheck/resendcode",
        orderGetValidateCode: "/weapp/v1/order/getvalidatecode",
        orderValidate: "/weapp/v1/order/validate",
        posname: "/weapp/v1/user/address/posname",
        addrGet: "/weapp/v1/user/address/getaddr",
        addrEdit: "/weapp/v1/user/address/edit",
        addrSearch: "/weapp/v1/user/address/search",
        addrSuggest: "/weapp/v1/user/address/suggest",
        addrNear: "/weapp/v1/user/address/nearby",
        cityName: "/weapp/v1/user/address/cityname",
        getcityList: "/weapp/v1/user/address/opencities",
        nearAddr: "/weapp/v1/user/address/nearby",
        searchHot: "/weapp/v1/search/home/hotlabelandhistory",
        verifyCodeSend: "/weapp/v1/account/sendverifycode",
        verifyCodeCheck: "/weapp/v1/account/checkverifycode",
        getMyAccount: "/weapp/v1/account/getmyaccount",
        accountLogin: "/weapp/v1/account/login",
        accountLoginV2: "/weapp/v2/account/login",
        logout: "/weapp/v2/account/logout",
        appleMobileV2: "/weapp/v2/account/applybindmobile",
        bindMobileV2: "/weapp/v2/account/bindmobilelogin",
        ticketLoginV2: "/weapp/v2/account/ticketlogin",
        mobileLogin: "/weapp/v2/account/getwxmobilelogin",
        pay: "/weapp/v1/payment/pay",
        refundPreview: "/weapp/v1/payment/refund/preview",
        refundSubmit: "/weapp/v1/payment/refund/submit",
        refundComplaints: "/weapp/v1/payment/refund/genrefundrep",
        refundComplaintsSubmit: "/weapp/v1/payment/refund/repsubmit",
        refundDetail: "/weapp/v1/payment/refund/detail",
        refundStatus: "/weapp/v2/payment/refundstatus",
        complaintPreview: "/weapp/v2/payment/complaint/preview",
        complaintSubmit: "/weapp/v2/payment/complaint/submit",
        getPoiCoupon: "/weapp/v1/activity/grabpoicoupon",
        getUserPoiCoupon: "/weapp/v1/user/poicoupons/getvalid",
        getCouponsList: "/weapp/v1/user/coupons/list",
        getPoiCouponsList: "/weapp/v1/user/poicoupons/list",
        getPoiCouponsNum: "/weapp/v1/user/poicoupons/num",
        getValidCoupons: "/weapp/v1/user/coupons/getvalid",
        couponDisableReason: "/weapp/v1/user/coupons/disablereason",
        getFoodlist: "/weapp/v1/order/getfoodlist",
        poiShare: "/weapp/v1/external/ajax/poi",
        foodComment: "/weapp/v1/comment/share/poi",
        grabPoiCouponByPhone: "/weapp/v1/activity/grabPoiCouponByPhone",
        poiShareFood: "/weapp/v1/external/poi/food",
        foodShare: "/weapp/v1/external/ajax/food",
        brandPoiList: "/weapp/v1/poi/brandpoilist",
        poiQualification: "/weapp/v1/poi/qualification",
        refundApplyPreview: "/weapp/v1/payment/refund/preview",
        refundApplySubmit: "/weapp/v2/payment/refund/submit",
        refundApplyCalculate: "/weapp/v2/payment/refund/calculate",
        productInfo: "/weapp/v2/poi/product/info",
        Muuid: "/weapp/v1/uuid",
        getThisCoupon: "/weapp/v1/activity/receivepoicoupon",
        bannerInfo: "/o/wxapp/home/marketing",
        getNewUserRedpackInfo: "/weapp/v1/newuser/entry",
        shareCart: "/weapp/v1/multiplecart/sharecart",
        curStatus: "/weapp/v1/multiplecart/curstatus",
        sponsorCancel: "/weapp/v1/multiplecart/cancel",
        partnerCancel: "/weapp/v1/multiplecart/quit",
        syncFood: "/weapp/v1/multiplecart/syncfood",
        pinInfo: "/weapp/v1/multiplecart/allcartinfo",
        pinStatus: "/weapp/v1/multiplecart/curstatus",
        allCartInfo: "/weapp/v1/multiplecart/allcartinfo",
        rcmdboard: "/weapp/v9/home/rcmdboard",
        uuidGray: "/weapp/v2/uuidgray"
    });
};